# 서버 포트
server.port=8080

# SQLite 파일 DB (data/busdb.db 파일로 저장됨)
spring.datasource.url=jdbc:sqlite:./data/busdb.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Thymeleaf
spring.thymeleaf.cache=false
